services:
  - type: web
    name: youtube-telegram-bot
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
